services:
  db:
    image: postgres:16
    container_name: db
    restart: on-failure
    env_file:
      - .env
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - .database:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      timeout: 7s
      retries: 5
  web-app:
    container_name: web-app
    image: web-app
    restart: on-failure
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:5000:5000"
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 5000"
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  migrations:
    image: web-app
    env_file:
      - .env
    command: alembic upgrade head
    depends_on:
      db:
        condition: service_healthy
