"""init

Revision ID: 54f80a9ed774
Revises:
Create Date: 2024-09-29 10:57:55.833237

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54f80a9ed774"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images", sa.Column("id", sa.UUID(), nullable=False), sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_images_id"), "images", ["id"], unique=False)
    op.create_table(
        "frames",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("image_id", sa.UUID(), nullable=False),
        sa.Column("depth", sa.Float(), nullable=False),
        sa.Column("points", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["images.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_frames_depth"), "frames", ["depth"], unique=False)
    op.create_index(op.f("ix_frames_id"), "frames", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_frames_id"), table_name="frames")
    op.drop_index(op.f("ix_frames_depth"), table_name="frames")
    op.drop_table("frames")
    op.drop_index(op.f("ix_images_id"), table_name="images")
    op.drop_table("images")
    # ### end Alembic commands ###
